import Link from 'next/link'
import { ArrowRight, Bot, Check, FileStack, FolderKanban, LockKeyhole, Network, Sparkles, Users2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { PublicAssistant } from '@/components/marketing/PublicAssistant'

export default function HomePage() {
  return <div className="min-h-screen bg-white text-orange-950"><nav className="sticky top-0 z-50 border-b border-orange-100 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-[1500px] items-center justify-between px-5"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ff6600] text-white"><Sparkles className="h-5 w-5" /></span><span><span className="block text-sm font-black tracking-tight">mybizz.io</span><span className="block text-[9px] font-bold uppercase tracking-[.2em] text-orange-600">AI Agency OS</span></span></Link><div className="hidden items-center gap-8 text-sm font-medium text-orange-950/60 md:flex"><Link href="/product" className="hover:text-orange-600">Platform</Link><Link href="/pricing" className="hover:text-orange-600">Pricing</Link><Link href="/start" className="hover:text-orange-600">Start a project</Link></div><div className="flex gap-2"><Button variant="ghost" asChild><Link href="/auth/login">Log in</Link></Button><Button className="bg-[#ff6600] text-white hover:bg-[#e95d00]" asChild><Link href="/start">Build with us <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></nav>
    <main><section className="relative overflow-hidden border-b border-orange-100"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(255,102,0,.12),transparent_30%),radial-gradient(circle_at_80%_70%,rgba(255,102,0,.08),transparent_28%)]" /><div className="relative mx-auto grid max-w-[1500px] gap-14 px-5 py-20 lg:grid-cols-[1fr_.9fr] lg:items-center lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-orange-200 bg-orange-50 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-orange-700"><span className="h-2 w-2 animate-pulse rounded-full bg-[#ff6600]" /> The operating system for ambitious digital work</div><h1 className="mt-7 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.065em] text-orange-950 sm:text-7xl xl:text-8xl">Your agency.<br /><span className="text-[#ff6600]">Now intelligent.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-orange-950/60">One striking workspace for client intake, delivery, documents, people and grounded AI—secured tenant by tenant from the first brief to launch.</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" className="h-13 bg-[#ff6600] px-7 text-white hover:bg-[#e95d00]" asChild><Link href="/start">Start your project <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button size="lg" variant="outline" className="h-13 border-orange-200 px-7 text-orange-950 hover:bg-orange-50" asChild><Link href="/auth/login">Enter Agency OS</Link></Button></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-orange-950/50">{['Clerk authentication','Supabase RLS','Zero-token grounded mode'].map((item) => <span key={item} className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#ff6600]" />{item}</span>)}</div></div><PublicAssistant /></div></section>
      <section className="mx-auto max-w-[1500px] px-5 py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#ff6600]">Agency OS</p><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.05em] sm:text-5xl">Signal, action and intelligence in one system.</h2></div><p className="max-w-md text-sm leading-6 text-orange-950/55">Every surface communicates with the same tenant-secured operational data. There are no decorative dead ends.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{features.map((feature) => <article key={feature.title} className="group rounded-3xl border border-orange-100 bg-white p-7 transition hover:-translate-y-1 hover:border-orange-300 hover:shadow-xl hover:shadow-orange-950/5"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-50 text-[#ff6600] transition group-hover:bg-[#ff6600] group-hover:text-white"><feature.icon className="h-5 w-5" /></span><h3 className="mt-6 text-lg font-bold">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-orange-950/55">{feature.description}</p></article>)}</div></section>
      <section className="bg-[#ff6600] text-white"><div className="mx-auto flex max-w-[1500px] flex-col items-start justify-between gap-8 px-5 py-20 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/65">Bring us the ambition</p><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.05em] sm:text-6xl">We’ll turn it into a system.</h2></div><Button size="lg" className="h-13 bg-white px-7 text-orange-700 hover:bg-orange-50" asChild><Link href="/start">Open the discovery wizard <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section></main><footer className="border-t border-orange-100 bg-white"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-4 px-5 py-8 text-xs text-orange-950/45 sm:flex-row"><span>© 2026 MyBizz. Built for better digital businesses.</span><span>Orange by conviction. Secure by design.</span></div></footer></div>
}

const features = [
  { title: 'Intelligent intake', description: 'The public wizard creates a structured client account and routes the brief directly into your secure pipeline.', icon: Network },
  { title: 'Delivery control room', description: 'Projects, accountable actions and immovable deadlines move together from discovery to launch.', icon: FolderKanban },
  { title: 'Grounded knowledge', description: 'Files become searchable evidence for local retrieval and cited answers without paid model tokens.', icon: FileStack },
  { title: 'Tenant-by-tenant security', description: 'Clerk proves identity and Supabase Row Level Security authorises every record operation.', icon: LockKeyhole },
  { title: 'Team access', description: 'Invite administrators and members into one client account at a time with auditable database membership.', icon: Users2 },
  { title: 'AI-shaped experience', description: 'Purpose-built assistants retrieve, rank and explain approved evidence while refusing to invent missing facts.', icon: Bot },
]
