import { Bot, Database, FileText, MessageSquare, ShieldCheck, Zap } from 'lucide-react'
import { requirePortalUser } from '@/lib/portal/auth'
import { getActiveOrganization } from '@/lib/portal/context'
import { createClient } from '@/lib/supabase/server'
import { PageHeader } from '@/components/portal/PageHeader'

export default async function AIUsagePage() {
  const user = await requirePortalUser()
  const membership = await getActiveOrganization(user.userId)
  const supabase = await createClient()
  const orgId = membership?.organization_id
  const [threads, messages, documents, chunks] = orgId ? await Promise.all([
    supabase.from('ai_threads').select('*', { count: 'exact', head: true }).eq('organization_id', orgId),
    supabase.from('ai_messages').select('*', { count: 'exact', head: true }).eq('organization_id', orgId),
    supabase.from('documents').select('*', { count: 'exact', head: true }).eq('organization_id', orgId),
    supabase.from('document_chunks').select('*', { count: 'exact', head: true }).eq('organization_id', orgId),
  ]) : [{ count: 0 }, { count: 0 }, { count: 0 }, { count: 0 }]
  return <div className="min-h-screen"><PageHeader eyebrow="Intelligence controls" title="Grounded AI operations" description="Retrieval quality, source coverage and spend controls for the active tenant." badge="£0 model spend" /><main className="mx-auto max-w-[1400px] space-y-6 p-5 sm:p-8 lg:p-10"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Paid tokens" value="0" icon={Zap} detail="Deterministic local mode" /><Metric label="Conversations" value={String(threads.count ?? 0)} icon={MessageSquare} detail={`${messages.count ?? 0} stored messages`} /><Metric label="Knowledge files" value={String(documents.count ?? 0)} icon={FileText} detail={`${chunks.count ?? 0} indexed passages`} /><Metric label="Tenant boundary" value="RLS" icon={ShieldCheck} detail={membership?.organizations?.name ?? 'No active tenant'} /></div><section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-orange-100 bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--agency-accent)] text-white"><Bot className="h-5 w-5" /></span><div><h2 className="font-semibold text-orange-950">How local grounded mode works</h2><p className="text-xs text-orange-950/45">AI-shaped interaction without an LLM bill</p></div></div><ol className="mt-7 space-y-5">{['The question is converted into a Postgres full-text query.', 'RLS removes every source outside the active tenant.', 'Relevant passages and approved platform knowledge are ranked.', 'A deterministic response composer explains the strongest evidence with sources.', 'Messages, citations and feedback are saved for audit and future model evaluation.'].map((text, index) => <li key={text} className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-orange-100 text-xs font-bold text-orange-800">{index + 1}</span><p className="text-sm leading-6 text-orange-950/65">{text}</p></li>)}</ol></div><div className="rounded-2xl bg-[var(--agency-accent)] p-7 text-white"><Database className="h-6 w-6" /><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-white/60">Current inference policy</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Evidence first.<br />No hallucinated certainty.</h2><div className="mt-8 space-y-3 text-sm text-white/75"><p>✓ Maximum 6 ranked passages</p><p>✓ Tenant membership required</p><p>✓ Public knowledge separated from client data</p><p>✓ Zero external model requests</p><p>✓ Easy upgrade path to hybrid vector search</p></div></div></section></main></div>
}

function Metric({ label, value, icon: Icon, detail }: { label: string; value: string; icon: typeof Zap; detail: string }) { return <div className="rounded-2xl border border-orange-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs text-orange-950/50">{label}</p><Icon className="h-4 w-4 text-[var(--agency-accent)]" /></div><p className="mt-2 text-3xl font-semibold text-orange-950">{value}</p><p className="mt-2 text-[10px] text-orange-950/40">{detail}</p></div> }
