import Link from 'next/link'
import { ArrowRight, BrainCircuit, Check, LockKeyhole, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'

const plans = [
  { key: 'free', name: 'Explorer', price: '£0', description: 'Prove the value on one live workspace.', cta: 'Start free', href: '/auth/sign-up', featured: false, features: ['3 Intelligence HQ runs / month', '5 grounded assistant questions / month', '1 indexed knowledge file', '1 member seat', '7-day intelligence history'] },
  { key: 'starter', name: 'Studio', price: '£49', description: 'A complete intelligence layer for a focused agency team.', cta: 'Request Studio', href: '/contact?plan=studio', featured: true, features: ['100 Intelligence HQ runs / month', '250 grounded assistant questions / month', '25 indexed knowledge files', '5 member seats', '90-day intelligence history'] },
  { key: 'pro', name: 'Scale', price: '£149', description: 'Portfolio-wide intelligence for a growing operator.', cta: 'Request Scale', href: '/contact?plan=scale', featured: false, features: ['500 Intelligence HQ runs / month', '2,000 grounded assistant questions / month', '250 indexed knowledge files', '20 member seats', 'Full intelligence history'] },
  { key: 'enterprise', name: 'Enterprise', price: 'Custom', description: 'Commercial controls, assurance and volume shaped around your operation.', cta: 'Talk to us', href: '/contact?plan=enterprise', featured: false, features: ['Custom intelligence volume', 'Custom seats and storage', 'Full intelligence history', 'Priority implementation support', 'Custom governance controls'] },
]

export const metadata = {
  title: 'Pricing — MyBizz Intelligence OS',
  description: 'Plans for tenant-secured operating intelligence, grounded assistants and Agency OS.',
}

export default function PricingPage() {
  return <div className="min-h-screen bg-white text-orange-950">
    <nav className="border-b border-orange-100 bg-white"><div className="mx-auto flex h-18 max-w-[1500px] items-center justify-between px-5"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ff6600] text-white"><Sparkles className="h-5 w-5" /></span><span><span className="block text-sm font-black">mybizz.io</span><span className="block text-[9px] font-bold uppercase tracking-[.2em] text-orange-600">Intelligence OS</span></span></Link><div className="flex items-center gap-2"><Button variant="ghost" asChild><Link href="/auth/login">Log in</Link></Button><Button className="bg-[#ff6600] text-white hover:bg-[#e95d00]" asChild><Link href="/auth/sign-up">Start free</Link></Button></div></div></nav>

    <main>
      <section className="relative overflow-hidden border-b border-orange-100 px-5 py-20 text-center sm:py-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,102,0,.15),transparent_36%)]" /><div className="relative mx-auto max-w-4xl"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-orange-200 bg-orange-50 px-4 py-2 text-[10px] font-bold uppercase tracking-[.18em] text-orange-700"><BrainCircuit className="h-3.5 w-3.5" />Commercial intelligence without token anxiety</div><h1 className="mt-7 text-5xl font-black tracking-[-.06em] sm:text-7xl">Start small.<br /><span className="text-[#ff6600]">Scale the signal.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-orange-950/55">Every plan includes Clerk authentication, database-enforced tenant isolation and explainable zero-token intelligence. Limits are enforced server-side for predictable control.</p></div></section>

      <section className="mx-auto max-w-[1500px] px-5 py-16 sm:py-20"><div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => <article key={plan.key} className={`relative flex flex-col rounded-3xl border p-7 ${plan.featured ? 'border-[#ff6600] bg-[#ff6600] text-white shadow-2xl shadow-orange-600/20' : 'border-orange-100 bg-white shadow-sm'}`}>{plan.featured && <span className="absolute -top-3 left-6 rounded-full bg-orange-950 px-3 py-1 text-[9px] font-bold uppercase tracking-[.16em] text-white">Best for agencies</span>}<div><p className={`text-[10px] font-bold uppercase tracking-[.18em] ${plan.featured ? 'text-white/60' : 'text-orange-600'}`}>{plan.name}</p><div className="mt-4 flex items-end gap-2"><span className="text-4xl font-semibold tracking-[-.05em]">{plan.price}</span>{plan.price.startsWith('£') && <span className={`pb-1 text-xs ${plan.featured ? 'text-white/55' : 'text-orange-950/35'}`}>/ month</span>}</div><p className={`mt-4 min-h-12 text-sm leading-6 ${plan.featured ? 'text-white/70' : 'text-orange-950/50'}`}>{plan.description}</p></div><ul className="mt-7 flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2.5 text-xs leading-5"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${plan.featured ? 'bg-white text-[#ff6600]' : 'bg-orange-100 text-orange-700'}`}><Check className="h-3 w-3" /></span><span className={plan.featured ? 'text-white/80' : 'text-orange-950/60'}>{feature}</span></li>)}</ul><Button className={`mt-8 h-11 w-full ${plan.featured ? 'bg-white text-orange-700 hover:bg-orange-50' : 'bg-orange-950 text-white hover:bg-orange-900'}`} asChild><Link href={plan.href}>{plan.cta}<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></article>)}</div>
        <div className="mt-8 grid gap-4 rounded-3xl border border-orange-100 bg-orange-50/60 p-6 md:grid-cols-3"><Value icon={LockKeyhole} title="Hard tenant boundary" body="Clerk proves identity; Supabase RLS authorises every organization record." /><Value icon={BrainCircuit} title="Explainable inference" body="Every brief exposes confidence, ranked signals and the sources that changed the answer." /><Value icon={Sparkles} title="No paid model spend" body="The current engine combines Postgres retrieval and deterministic reasoning without an AI API key." /></div>
      </section>

      <section className="bg-orange-950 px-5 py-20 text-white"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-orange-300">Explorer is genuinely free</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Three real intelligence runs.<br />No card. No pretend demo.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-white/55">When your allowance is used, the workspace stays available and shows a clear plan comparison. Your tenant data is never removed to force an upgrade.</p></div><Button size="lg" className="h-12 shrink-0 bg-[#ff6600] px-7 text-white hover:bg-[#e95d00]" asChild><Link href="/auth/sign-up">Create your workspace <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
    </main>
    <footer className="border-t border-orange-100 px-5 py-8"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-3 text-xs text-orange-950/40 sm:flex-row"><span>© 2026 MyBizz. Intelligence for better digital businesses.</span><span>Orange by conviction. Secure by design.</span></div></footer>
  </div>
}

function Value({ icon: Icon, title, body }: { icon: typeof BrainCircuit; title: string; body: string }) { return <div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#ff6600] text-white"><Icon className="h-4 w-4" /></span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-orange-950/45">{body}</p></div></div> }
